name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега, начинающегося с 'v'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry config virtualenvs.create true
        
    - name: Install dependencies
      run: |
        poetry install --no-dev
        poetry add --group dev pyinstaller
      
    - name: Build executable
      run: |
        poetry run pyinstaller --onefile --windowed --name SalaryReader --icon=src/salary_reader/resources/images/export-icon.png src/salary_reader/main.py
        
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SalaryReader.exe
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
